$js = [System.IO.File]::ReadAllText('js\report.js')

$js = $js -replace '(?s)downloadOnePagePDF: function \(\) \{.*?(?=downloadOnePageImage: function \(\) \{)', "downloadOnePagePDF: function () { const element = document.getElementById('reportElement'); this._prepareForExport(element); const controlBar = document.querySelector('.report-control-bar'); if(controlBar) controlBar.style.display = 'none'; try { if (typeof html2pdf === 'undefined') { console.error('html2pdf is missing'); if(controlBar) controlBar.style.display = 'flex'; return; } const opt = { margin: [5, 5, 5, 5], filename: `${this.currentOp} - ${this.currentDateYMD}.pdf`, image: { type: 'jpeg', quality: 1.0 }, html2canvas: { scale: 2, useCORS: true, letterRendering: true, backgroundColor: '#f1f5f9', scrollY: 0 }, jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' } }; html2pdf().set(opt).from(element).save().then(() => { if(controlBar) controlBar.style.display = 'flex'; }).catch(err => { console.error(err); if(controlBar) controlBar.style.display = 'flex'; }); } catch(e) { console.error(e); if(controlBar) controlBar.style.display = 'flex'; } },`n`n    "

$js = $js -replace '(?s)downloadOnePageImage: function \(\) \{.*?(?=downloadProfessionalPDF: function \(\) \{)', "downloadOnePageImage: function () { const element = document.getElementById('reportElement'); this._prepareForExport(element); const controlBar = document.querySelector('.report-control-bar'); if(controlBar) controlBar.style.display = 'none'; try { if (typeof html2canvas === 'undefined') { console.error('html2canvas is missing'); if(controlBar) controlBar.style.display = 'flex'; return; } html2canvas(element, { scale: 2, useCORS: true, backgroundColor: '#f1f5f9', scrollY: 0 }).then(canvas => { const link = document.createElement('a'); link.download = `${this.currentOp} - ${this.currentDateYMD}.png`; link.href = canvas.toDataURL('image/png', 1.0); link.click(); if(controlBar) controlBar.style.display = 'flex'; }).catch(err => { console.error(err); if(controlBar) controlBar.style.display = 'flex'; }); } catch(e) { console.error(e); if(controlBar) controlBar.style.display = 'flex'; } },`n`n    "

$js = $js -replace '(?s)downloadProfessionalPDF: function \(\) \{.*?(?=toggleSafetyGeneralPanel: function \(\) \{)', "downloadProfessionalPDF: function () { const element = document.getElementById('reportElement'); this._prepareForExport(element); const existingLines = element.querySelectorAll('.preview-break-line'); existingLines.forEach(l => l.style.display = 'none'); const controlBar = document.querySelector('.report-control-bar'); if(controlBar) controlBar.style.display = 'none'; try { if (typeof html2pdf === 'undefined') { console.error('html2pdf is missing'); if(controlBar) controlBar.style.display = 'flex'; existingLines.forEach(l => l.style.display = 'block'); return; } const opt = { margin: [10, 10, 10, 10], filename: `${this.currentOp} - ${this.currentDateYMD} (Profissional).pdf`, image: { type: 'jpeg', quality: 1.0 }, html2canvas: { scale: 2, useCORS: true, letterRendering: true, backgroundColor: '#f1f5f9', scrollY: 0 }, jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' }, pagebreak: { mode: ['css', 'legacy'] } }; html2pdf().set(opt).from(element).save().then(() => { if(controlBar) controlBar.style.display = 'flex'; existingLines.forEach(l => l.style.display = 'block'); }).catch(err => { console.error(err); if(controlBar) controlBar.style.display = 'flex'; existingLines.forEach(l => l.style.display = 'block'); }); } catch(e) { console.error(e); if(controlBar) controlBar.style.display = 'flex'; existingLines.forEach(l => l.style.display = 'block'); } },`n`n    "

[System.IO.File]::WriteAllText('js\report.js', $js)
